apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
  labels:
    app.kubernetes.io/name: telemetry
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: cluster-telemetry-bundle
    app.kubernetes.io/managed-by: flux
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
