apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-target-allocator-cluster-values
  namespace: telemetry
  labels:
    app.kubernetes.io/name: opentelemetry-target-allocator-cluster-values
    app.kubernetes.io/component: metrics-discovery
    app.kubernetes.io/part-of: cluster-telemetry-bundle
    app.kubernetes.io/managed-by: flux
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    targetAllocator:
      config:
        prometheus_cr:
          service_monitor_selector:
            matchLabels:
              telemetry.example.com/scrape: "true"
          pod_monitor_selector:
            matchLabels:
              telemetry.example.com/scrape: "true"
