apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cluster-us-east-1-prometheus-crds
components:
  - ../../base/components/kube-state-metrics
  - ../../base/components/node-exporter
