apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: telemetry
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: cluster-telemetry-bundle
    app.kubernetes.io/managed-by: flux
spec:
  interval: 1h
  timeout: 5m
  dependsOn:
    - name: opentelemetry-collector
  chart:
    spec:
      chart: fluent-bit
      version: "0.56.0"
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: fluent-bit-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: fluent-bit-cluster-values
      valuesKey: values.yaml
      optional: true
