apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent-bit
  namespace: telemetry
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: cluster-telemetry-bundle
    app.kubernetes.io/managed-by: flux
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/fluent/helm-charts
