apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: telemetry
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: processing
    app.kubernetes.io/part-of: cluster-telemetry-bundle
    app.kubernetes.io/managed-by: flux
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts
