apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-telemetry-bundle
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cotocisternas/cluster-telemetry-bundle.git
  ref:
    branch: main
